
export enum KeyboardKey {
    ENTER = "Enter",

    DIGIT_0 = "Digit0",
    DIGIT_1 = "Digit1",
    DIGIT_2 = "Digit2",
    DIGIT_3 = "Digit3",
    DIGIT_4 = "Digit4",
    DIGIT_5 = "Digit5",
    DIGIT_6 = "Digit6",
    DIGIT_7 = "Digit7",
    DIGIT_8 = "Digit8",
    DIGIT_9 = "Digit9",

    SPACE = "Space",

    A = "KeyA",
    B = "KeyB",
    C = "KeyC",
    D = "KeyD",
    E = "KeyE",
    F = "KeyF",
    G = "KeyG",
    H = "KeyH",
    I = "KeyI",
    J = "KeyJ",
    K = "KeyK",
    L = "KeyL",
    M = "KeyM",
    N = "KeyN",
    O = "KeyO",
    P = "KeyP",
    Q = "KeyQ",
    R = "KeyR",
    S = "KeyS",
    T = "KeyT",
    U = "KeyU",
    V = "KeyV",
    W = "KeyW",
    X = "KeyX",
    Y = "KeyY",
    Z = "KeyZ",

    LEFT = "ArrowLeft",
    UP = "ArrowUp",
    RIGHT = "ArrowRight",
    DOWN = "ArrowDown",

    ALT = "AltLeft",
    BACKSPACE = "Backspace",
    CAPS_LOCK = "CapsLock",
    ESC = "Escape",
    CONTROL = "ControlLeft",
    SHIFT = "ShiftLeft",

    PAUSE_BREAK = "Pause",
    DELETE = "Delete",
    HOME = "Home",
    END = "End",
    TAB = "Tab",

    PAGE_UP = "PageUp",
    PAGE_DOWN = "PageDown",
    INSERT = "Insert",

    PLUS = "Equal",
    MINUS = "Minus",

    NUMPAD_0 = "Numpad0",
    NUMPAD_1 = "Numpad1",
    NUMPAD_2 = "Numpad2",
    NUMPAD_3 = "Numpad3",
    NUMPAD_4 = "Numpad4",
    NUMPAD_5 = "Numpad5",
    NUMPAD_6 = "Numpad6",
    NUMPAD_7 = "Numpad7",
    NUMPAD_8 = "Numpad8",
    NUMPAD_9 = "Numpad9",

    NUMPAD_MULT = "NumpadMultiply",
    NUMPAD_ADD = "NumpadAdd",
    NUMPAD_SUBTRACT = "NumpadSubtract",
    NUMPAD_DECIMAL_POINT = "NumpadDecimal",
    NUMPAD_DIVIDE = "NumpadDivide",

    NUM_LOCK = "NumLock",
    SCROLL_LOCK = "ScrollLock",

    F1 = "F1",
    F2 = "F2",
    F3 = "F3",
    F4 = "F4",
    F5 = "F5",
    F6 = "F6",
    F7 = "F7",
    F8 = "F8",
    F9 = "F9",
    F10 = "F10",
    F11 = "F11",
    F12 = "F12",

    BACK_QUOTE = "Backquote",
    BACKSLASH = "Backslash",

    WINDOW_LEFT = "MetaLeft",
    WINDOW_RIGHT = "MetaRight",

    // KaiOS specific cell phone buttons

    SOFT_RIGHT = "SoftRight",
    SOFT_LEFT = "SoftLeft",
    CALL = "Call",
    END_CALL = "EndCall",
    STAR = "Star",
    HASH = "Hash",
    SLASH = "Slash",
}
